### ISSUE TITLE
等更新歌词

### ISSUE THREAD

**Issue by forsnowlove** [shinyawhy/QooMusicPlayer#1]
封面地址报错 win10 QT5.14
封面地址： "https://p2.music.126.net/05SKrkDNNgrwxzC_JqLqiA==/72567767449520.jpg"
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
warning: 下载的封面是空的 "A.I.N.Y.-G.E.M.邓紫棋"

**Comment by shinyawhy** [comment]
这是系统libcrypto-1_1.dll和libssl-1_1.dll这俩文件的问题，需要在程序debug文件夹下添加这两个dll以及qt安装路径下添加这俩个dll
